export enum ServiceName {
  HARDWARE_MONITOR = 'hardwareMonitor',
  HARDWARE_MANAGEMENT = 'hardwareManagement',
  PI_HOLE = 'piHole',
  INDOOR_WEATHER_STATION = 'indoorWeatherStation',
  OUTDOOR_WEATHER_STATION = 'outdoorWeatherStation',
  OPEN_WEATHER_AIR_QUALITY = 'openWeatherAirQuality',
  OPEN_WEATHER_FORECAST = 'openWeatherForecast',
  PRINT_SERVER = 'printServer',
  MOTION_SENSORS = 'motionSensors',
  PARKING_CAMERAS = 'parkingCameras',
  MAIN_LIGHTS_CONTROL = 'mainLightsControl',
  DECORATIVE_LIGHTS_CONTROL = 'decorativeLightsControl',
  SPOTIFY = 'spotify',
}
